[package]
name = "ranger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
crossterm = "0.28.1"
dialoguer = "0.11.0"
reqwest = "0.12.8"
tokio = { version = "1.41.0", features = ["full"] }
